Activity Types (coded 1-6)

1 WALKING
2 WALKING_UPSTAIRS
3 WALKING_DOWNSTAIRS
4 SITTING
5 STANDING
6 LAYING

Test subjects identified and uniquely numbered 1 thru 30

This dataset makes use of the features defined in the UCI HAR Dataset, shown below. 

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag

Please reference the detailed data specification here:


for more information on the technical aspects of collection and processing. The current data were generated by taking an subset of the orignal data. The '-XYZ' 3-axial signals for the X, Y and Z directions are still utilized, but only the following measures were extracted:

mean(): Mean value
std(): Standard deviation

To generate the final output, the full dataset was grouped by Activity Type and Subject and the means of each feature for each grouping was calculated and output in a text file.
